from panflute.table_elements import Caption
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
)

def check_group(value: str, group: Set[str]) -> str: ...
def check_type(value: Any, oktypes: Any) -> Any: ...
def check_type_or_value(
    value: Union[str, Caption, float],
    oktypes: Union[Tuple[Type[float], Type[int]], Type[Caption]],
    okvalue: Optional[str],
) -> Union[str, Caption, float]: ...
def debug(*args, **kwargs) -> None: ...
def decode_ica(
    lst: List[Union[str, List[List[str]], List[str]]]
) -> Dict[str, Union[str, List[str], List[List[str]]]]: ...
def encode_dict(tag: str, content: Any) -> Dict[str, Any]: ...
def load_pandoc_reader_options() -> Dict[Any, Any]: ...
def load_pandoc_version() -> None: ...

class ContextImport:
    def __exit__(self, exc_type: None, exc_value: None, traceback: None) -> None: ...
    def __init__(self, module: str, extra_dir: Optional[str] = ...) -> None: ...
